### ISSUE TITLE
Expand without attributes

### ISSUE THREAD

**Issue by skube** [emmetio/expand-abbreviation#1]
Not sure if there is the correct place to request this but I was wondering if it's possible to expand without attributes.

For example:

When using label, it's not required to use the `for=""` attribute if the `input` is nested inside.

However expanding `label` results in `<label for="|">|</label>` which means I have to go back and delete the ` for=""`

It would be nice if one could suppress attributes from time to time.

**Comment by sergeche** [comment]
You should either create a new snippet or override existing one for a label without `for` attribute
