### ISSUE TITLE
Allow setting of css.fuzzySearchMinScore

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/expand-abbreviation#10]
In the old emmet model, the css.fuzzySearchMinScore was set to 0.3 by default.
Therefore `auto` would never get expanded to anything.

In the new emmet model, there is no way to set the css.fuzzySearchMinScore
And so `auto` gets expanded to `align-self: auto` And this match as a score of 0.166

The [css-snippets-resolver](https://github.com/emmetio/css-snippets-resolver) should be updated to taken in a css.fuzzySearchMinScore to use the same default of 0.3 as before

cc @sergeche

**Comment by sergeche** [comment]
What’s the context of `auto` value as property?
This option can be easily added to `findBestMatch()` function and passed from expander options

**Comment by ramya-rao-a** [comment]
In this case user was typing `overflow: auto`. Since we are providing emmet via intellisense/suggestions, `auto` gets passed to emmet for expansions.

Yes, scope checks can pre-empt such requests, but we don't have that option in VS Code for extensions.

Regardless, I am not very keen on adding the minScore as a customizable input. Is it ok if I send a PR to hard-code 0.3 as a min score and we can pass it via options in the future if there is a need to customize it?

**Comment by sergeche** [comment]
No, hard coding isn’t an option: it’s very easy to break other completions.
For your case, you can re-use `@emmetio/css-parser` to get CSS scope for completions

**Comment by ramya-rao-a** [comment]
@sergeche One scenario where CSS scope fails is when using snippets like `trf:r`

Here at the end of `trf:r` the CSS parser assumes that you are now inside the "value" part of the "property-value" pair

Thus, instead of checking for the scope I need to bank on setting a min value for the fuzzyMatchingScore

I have submitted a PR https://github.com/emmetio/css-snippets-resolver/pull/7.
Please take a look
