### ISSUE TITLE
Final tab stop doesnt get added in the snippet

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/expand-abbreviation#11]
When presenting snippets, editors (atleast VS Code) adds a `${0}` (the final tabstop) in the end of the snippet if `${0}` doesnt exist in the snippet itself

In the old Emmet, `ul` got expanded to `<ul>${0}</ul>`
In the new Emmet `ul` gets expanded to `<ul>${1}</ul>` which in VS Code ends up as `<ul>${1}</ul>${0}` which is not productive or intuitive to the users.

@sergeche Is there any reason for this change in behavior?

**Comment by sergeche** [comment]
AFAIK `${0}` is actually a final tabstop in editors like TextMate and Sublime Text: they move caret to `${0}` after you hit Enter to exit tabstop mode. So general idea was to exclude `${0}` completely from Emmet formatter output so you can control final caret position

**Comment by ramya-rao-a** [comment]
`${0}` is a final tab stop in VS Code as well.

Editors will not have the knowledge of where the final caret position should go in Emmet snippets.
Only Emmet would know this.
So editors trying to guess where the final caret position should go seems inefficient and prone to bugs.

**Comment by ramya-rao-a** [comment]
@sergeche ping

**Comment by sergeche** [comment]
Not sure what I have to to with this issue. Since every tabstob is outputted via custom function passed to expander, it’s up to editor to decide how to output/change tabstop indices and how final tabstop should look like

**Comment by ramya-rao-a** [comment]
By custom function you mean the `field` that gets passed to the `options`?

We use `(index, placeholder) => `\${${index}${placeholder ? ':' + placeholder : ''}}``

How can the editor specify anything about the final tab stop via the `field`?

The decision of where the final tab stop should be can be only taken by Emmet.
The decision of what the final tab stop should "look" like can be taken by the Editor.

**Comment by sergeche** [comment]
The final tabstop is always placed at the end of generated snippet, this is how it works in Sublime Text. By default, it’s `${0}`, which is treated by editor as a place where caret should be when user exits tabstop mode. If you need `${MAX_INDEX + 1}` tabstop, you can calculate max index via `field` function passed to abbreviation expander

**Comment by ramya-rao-a** [comment]
Closing this issue as I have taken care of this on the editor's side for VS Code
