### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lifeiscontent** [emmetio/expand-abbreviation#12]
Hey there!

I just created an emmet plugin for sketch. is there a place you guys showcase all the working implementations of emmet?

if so. where can I add this one? https://github.com/lifeiscontent/emmet-sketch

**Comment by sergeche** [comment]
No, currently, there’s no showcase for Emmet-based plugins

**Comment by lifeiscontent** [comment]
@sergeche okay, thanks!
