### ISSUE TITLE
Char error on expand

### ISSUE THREAD

**Issue by GGGGino** [emmetio/expand-abbreviation#13]
Hi,

When i expand a string like `"div.container{try'label}"` it throws `Uncaught Error: Unable to consume quoted string at char 18`.

If i use `"div.container{trylabel}"` it expands properly
I didn't tried any other special character.

**Comment by ramya-rao-a** [comment]
This is tracked in https://github.com/emmetio/abbreviation/issues/8 which has now been fixed.

@sergeche You can close this one
