### ISSUE TITLE
Preserve user-defined order of attributes

### ISSUE THREAD

**Issue by sergeche** [emmetio/expand-abbreviation#16]
Original issue: https://github.com/emmetio/emmet/issues/331

The order of attributes in output should be controlled by user, e.g. `a.test[href=#]` should expand to `<a class="test" href="#">`, not `<a href="#" class="test">`.

This feature must be controlled by hidden user option.

**Comment by rreeppeeaatteerr** [comment]
+1
I find it very helpful to have all my class names up front, right after the tag opening. Keeps things pretty and consistent!

**Comment by toby3d** [comment]
Some organizations and/or projects require a certain style of code and this feature could be very useful.

**Comment by nikolaykrylov** [comment]
Is this enhancement done?

**Comment by OBats** [comment]
+1

It would be very useful!

**Comment by kapreski** [comment]
+1

**Comment by ArtemVeremienko** [comment]
+1

**Comment by venskou** [comment]
+1

**Comment by ivanlyu** [comment]
+1

**Comment by yeah-not** [comment]
+1

**Comment by sergeche** [comment]
Implemented as `output.reverseAttributes` option in upcoming v2: https://github.com/emmetio/emmet/blob/master/src/config/types.ts#L111
