### ISSUE TITLE
CSS abbreviation with + at the end doesn't get expanded properly

### ISSUE THREAD

**Issue by gushuro** [emmetio/expand-abbreviation#19]
When expanding `bg+`, I get the expansion of `bg` instead of the full one described in the cheat sheet, `background:#fff url() 0 0 no-repeat;`
Interestingly, I get different behavior for `f+`

**Comment by sergeche** [comment]
Abbreviations with `+` at the end are deprecated since `+` is a combining operator and it introduces unneeded complexity

**Comment by gushuro** [comment]
Alright, thanks for clarifying!
