### ISSUE TITLE
In jsx, class attribute should be "className" not "class"

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/expand-abbreviation#2]
The abbr `hello.bye` should expand to `<hello className="bye"></hello>` in jsx syntax and not  `<hello class="bye"></hello>`

**Comment by ramya-rao-a** [comment]
@sergeche ping

**Comment by sergeche** [comment]
Make sure you’ve enabled `jsx` addon: https://github.com/emmetio/expand-abbreviation/blob/master/index.js#L93

**Comment by ramya-rao-a** [comment]
Thanks, that worked!
