### ISSUE TITLE
Remove "action" from form completion, or make an option

### ISSUE THREAD

**Issue by smlombardi** [emmetio/expand-abbreviation#21]
Issue Type: <b>Feature Request</b>

Emmet completes `form` as `form action=""`.  In this day and age, using Angular and other frameworks I almost never need an `action` and I always need to delete it.

Can this  be removed from the default suggestion?  Or, at least, have it pre-selected for easy deletion, as in `${1:action="$2"}`?

**Comment by sergeche** [comment]
An ultimate solution is to remove `action` attribute in your own snippets. Would be significantly easier to do so in next Emmet version: http://github.com/emmetio/emmet
