### ISSUE TITLE
lorem*2 expands to a single line of lorem instead of 2

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/expand-abbreviation#23]
`lorem*2` expands to a single line of lorem
`lorem*3` expands to two lines of lorem

When trying out lorem in https://docs.emmet.io/, I noticed that `lorem*n` always surrounded the text by a `div` tag when `n` > 1

But the new emmet modules dont do this and so end up becoming an inline element and forced to follow the `inline_break` configuration.

cc @sergeche

**Comment by sergeche** [comment]
Fixed in https://github.com/emmetio/emmet/commit/1a7ff1acfadf68b54069d6b35b61ef95bbc8b2d3
