### ISSUE TITLE
p(lorem10) is not a valid abbreviation anymore

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/expand-abbreviation#24]
@sergeche 

 `(p)lorem2` is a valid abbreviation as per https://docs.emmet.io/ and expands to `<p>Lorem, ipsum.</p>`
But it is no longer a valid abbreviation as per the new `expand-abbreviation` modules

**Comment by ramya-rao-a** [comment]
@sergeche Thoughts?

**Comment by sergeche** [comment]
Fixed in new Emmet implementation: http://github.com/emmetio/emmet
