### ISSUE TITLE
Loading settings via the codemirror-plugin

### ISSUE THREAD

**Issue by jeffadev** [emmetio/expand-abbreviation#4]
Hey, @sergeche.

I can't seem to get the settings for expand-abbreviation, i.e. `addons: { jsx: true }`.

Here is my current code that is setting the `emmet` variable in the CodeMirror settings:
```javascript
this.codemirror.setOption('emmet', {
  addons: {
    jsx: true,
  },
});
```

Emmet is fully functioning, as I can use it in the editor, but I am in need of getting the JSX addon working.

**Comment by sergeche** [comment]
Fixed in v0.3.5 of CodeMirror plugin
