### ISSUE TITLE
Expand multiplication of group returns nothing.

### ISSUE THREAD

**Issue by yume-chan** [emmetio/expand-abbreviation#7]
When using multiplication with grouping, for example `(div)*2`, the old implementation returns `"<div></div><div></div>"`, but this package returns `""`.

**Comment by ramya-rao-a** [comment]
https://github.com/emmetio/output-renderer/commit/6e1186db49e74094aaeda83c67bfb3b84712320f fixed this issue

@sergeche  you can close this one.
