### ISSUE TITLE
Formatter for css doesn't work as expected

### ISSUE THREAD

**Issue by ramya-rao-a** [emmetio/expand-abbreviation#8]
I tried to add the below test for css. It fails.

```
	it('uses format', () => {
		assert.equal(expand('p10', {
			format: {
				between: "::",
				after: ";;"
			}
		}), 'padding::10px;;');
	});
```

It passes only when an extra level of `format` is passed in
```
	it('uses format', () => {
		assert.equal(expand('p10', {
			format: {
				"format": {
					between: "::",
					after: ";;"
				}
			}
		}), 'padding::10px;;');
	});
```

**Comment by ramya-rao-a** [comment]
I would expect something like the below to work though

```
	it('uses format', () => {
		assert.equal(expand('p10', {
			format: {
				"css": {
					between: "::",
					after: ";;"
				}
			}
		}), 'padding::10px;;');
	});
```


Which model do you prefer @sergeche?

**Comment by sergeche** [comment]
I think it should be

```
it('uses format', () => {
	assert.equal(expand('p10', {
		css: {
			between: "::",
			after: ";;"
		}
	}), 'padding::10px;;');
});
```

**Comment by ramya-rao-a** [comment]
There should a `format` key in the `options`. `css` can't be the direct child under `options`.

For eg: In the test for the comment formatter you have
`expand('ul>li.item*2', {format: {comment: {enabled: true}})`

So for css formatter it should be
`expand('p10', {format: {css: {between: ":", after: ";"}}})`

**Comment by ramya-rao-a** [comment]
This is what I suggest the options to look like say for css

```json
{
    "syntax": "css",
    "format": {
        "stylesheet": {
             "between": ":",
             "after": ";",
             "unitAliases": {
              },
             "intUnit": "px",
             "floatUnit": "em"
         }
    }
}
```

We don't need to have `css` as a key inside `format` because for a given call to expand the syntax would already specify that.

The child of `format` should be the formatter's name. Eg: `comment`, `stylesheet`
